apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-node
  namespace: rbd-system
  labels:
    belongTo: rainbond-operator
    creator: Rainbond
    name: rbd-node
    priorityComponent: "true"
    persistentVolumeClaimAccessModes: ReadWriteOnce
spec:
  replicas: 1
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-node:V5.8-dev
  imagePullPolicy: IfNotPresent
  priorityComponent: true
  volumeMounts:
    - mountPath: /run/containerd/containerd.sock
      name: containerdsock
  volumes:
    - hostPath:
        path: /run/k3s/containerd/containerd.sock
        type: Socket
      name: containerdsock