apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-monitor
  namespace: rbd-system
  labels:
    belongTo: rainbond-operator
    creator: Rainbond
    name: rbd-monitor
spec:
  replicas: 1
  image: rainbond/rbd-monitor:v5.6.0-release
  imagePullPolicy: IfNotPresent
  priorityComponent: false
  resources:
    requests:
      memory: 0
      cpu: 0
    limits:
      memory: 0
      cpu: 0
