groups:
  - name: BuilderHealth
    rules:
      - alert: BuilderDown
        expr: absent(up{component="builder"}) or up{component="builder"}==0
        for: 1m
        labels:
          Alert: Rainbond
          PageAlarm: "true"
          Region: cloud
        annotations:
          description: 构建组件(rbd-chaos) {{ $labels.instance }} 出现故障
          summary: 构建组件(rbd-chaos)故障
      - alert: BuilderUnhealthy
        expr: builder_exporter_health_status == 0
        for: 3m
        labels:
          Alert: Rainbond
          PageAlarm: "true"
          Region: cloud
        annotations:
          description: 构建组件(rbd-chaos) {{ $labels.instance }} 不健康
      - alert: BuilderTaskError
        expr: builder_exporter_builder_current_concurrent_task == builder_exporter_builder_max_concurrent_task
        for: 20s
        labels:
          Alert: Rainbond
          PageAlarm: "true"
          Region: cloud
        annotations:
          summary: 构建组件(rbd-chaos)并发执行任务数量达到最大,负载过高
  - name: WorkerHealth
    rules:
      - alert: WorkerDown
        expr: absent(worker_exporter_health_status) or worker_exporter_health_status==0
        for: 5m
        labels:
          Alert: Rainbond
          PageAlarm: "false"
          Region: cloud
        annotations:
          description: rbd-worker组件 {{ $labels.instance }} 出现故障
          summary: rbd-worker组件故障
      - alert: WorkerUnhealthy
        expr: app_resource_exporter_health_status == 0
        for: 5m
        labels:
          Alert: Rainbond
          PageAlarm: "false"
          Region: cloud
        annotations:
          description: rbd-worker组件 {{ $labels.instance }} 不健康
          summary: rbd-worker组件不健康
      - alert: WorkerTaskError
        expr: worker_exporter_worker_task_error >10
        for: 5m
        labels:
          Alert: Rainbond
          PageAlarm: "true"
          Region: cloud
        annotations:
          description: rbd-worker组件 {{ $labels.instance }} 执行任务错误数大于10
  - name: MqHealth
    rules:
      - alert: MqDown
        expr: absent(up{component="mq"}) or up{component="mq"}==0
        for: 2m
        labels:
          Alert: Rainbond
          PageAlarm: "true"
          Region: cloud
        annotations:
          description: 消息队列组件(rbd-mq) {{ $labels.instance }} 出现故障
          summary: 消息队列组件(rbd-mq)出现故障
      - alert: MqUnhealthy
        expr: acp_mq_exporter_health_status == 0
        for: 3m
        labels:
          Alert: Rainbond
          PageAlarm: "true"
          Region: cloud
        annotations:
          summary: 消息队列组件(rbd-mq)不健康
      - alert: MqMessageQueueBlock
        expr: acp_mq_queue_message_number > 0
        for: 1m
        labels:
          Alert: Rainbond
          PageAlarm: "true"
          Region: cloud
        annotations:
          description: 消息 {{ $labels.topic }} 阻塞, 消息大小为 {{ humanize $value }}
          summary: 消息队列阻塞

  - name: ClusterHealth
    rules:
      - alert: InsufficientClusteMemoryResources
        expr: max(rbd_api_exporter_cluster_memory_total) - max(sum(namespace_resource_memory_request)
          by (instance)) < 2048
        for: 2m
        labels:
          Alert: Rainbond
          PageAlarm: "false"
          Region: cloud
        annotations:
          description: 集群剩余调度内存为 {{ humanize $value }} MB, 不足2048MB
          summary: 集群内存资源不足
      - alert: InsufficientClusteCPUResources
        expr: max(rbd_api_exporter_cluster_cpu_total) - max(sum(namespace_resource_cpu_request)
          by (instance)) < 500
        for: 2m
        labels:
          Alert: Rainbond
          PageAlarm: "false"
          Region: cloud
        annotations:
          description: 集群剩余调度cpu资源为 {{ humanize $value }}, 不足500m
          summary: 集群cpu资源不足
      - alert: InsufficientTenantResources
        expr: sum(rbd_api_exporter_tenant_memory_limit) by(namespace) - sum(namespace_resource_memory_request)by
          (namespace) < sum(rbd_api_exporter_tenant_memory_limit) by(namespace) *0.2 and
          sum(rbd_api_exporter_tenant_memory_limit) by(namespace) > 0
        for: 2m
        labels:
          Alert: Rainbond
          PageAlarm: "true"
          Region: cloud
        annotations:
          description: 租户剩余可用内存容量为 {{ humanize $value }} MB, 不足限制的20%
          summary: 租户内存资源不足
  - name: APIHealth
    rules:
      - alert: APIDown
        expr: absent(up{job="rbdapi"}) or up{job="rbdapi"}==0
        for: 1m
        labels:
          Alert: Rainbond
          PageAlarm: "true"
          Region: cloud
        annotations:
          description: rbd-api组件 {{ $labels.instance }} 出现故障
          summary: rbd-api组件故障